const SUCCESS_CODE = 200;
const NOT_FOUND = 404;
const SERVER_ERROR = 500;
const DATA_ALREADY_EXISTS = 409;
const UN_AUTHORIZED = 401;
const BAD_REQUEST = 400;
const FORBIDDEN = 403;
const PARTIAL_CONTENT_SUCCESS = 206;
const UNSUPPORTED_MEDIA_TYPE = 415;
const SESSION_EXPIRED = 440;

module.exports = {
  SUCCESS_CODE, 
  NOT_FOUND,
  SERVER_ERROR,
  DATA_ALREADY_EXISTS,
  UN_AUTHORIZED,
  BAD_REQUEST,
  FORBIDDEN,
  PARTIAL_CONTENT_SUCCESS,
  UNSUPPORTED_MEDIA_TYPE,
  SESSION_EXPIRED
};
